import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthContext from "./context/AuthContext";
import ClientOnly from "./components/ClientOnly";
import Navbar from "./components/navbar/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={poppins.className}>
        <div className="dark:bg-black transition-colors">
          <AuthContext>
            <ClientOnly>
              <Navbar />
            </ClientOnly>
            {children}
          </AuthContext>
        </div>
      </body>
    </html>
  );
}
